# Registry and repository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: esara
  version: latest
  pullPolicy: IfNotPresent

# Pod Security Policy
psp:
  enabled: false

# For the mini ones minikube, minishift set to true
nodeport: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

ocCreateRoute: false

otlp:
  endpoint: http://opentelemetry-collector.monitoring.svc.cluster.local:4317
  insecure: true

######################################
# Affinities for individual workloads
# set in the following way:
# <workload>:
#   affinity: {}
#   nodeSelector: {}
#   tolerations: []
######################################

cart:
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: cart
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app

catalogue: 
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: catalogue
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app

dispatch: 
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: dispatch
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app

mongodb:
  tolerations:
    - key: "persistent"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    workload: persistent

mysql:
  tolerations:
    - key: "persistent"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    workload: persistent

payment:
  replicas: 2
  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  gateway: null
  #gateway: https://www.worldpay.com
#  failureHour: 20
#  failureFromMinute: 30
#  failureTillMinute: 60
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: payment
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app

shipping: 
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: shipping
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app
#  failureHour: null
#  failureFromMinute: 0
#  failureTillMinute: 15

rabbitmq:
  replicas: 3
  enableExporter: true
  tolerations:
    - key: "persistent"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    workload: persistent

ratings: 
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: ratings
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app

redis:
  # Storage class to use with redis statefulset.
  storageClassName: gp2
  tolerations:
    - key: "persistent"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    workload: persistent

user:
  replicas: 2 
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: user
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app

web:
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            service: web
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    workload: app
