apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas:  {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: payment
        image: {{ .Values.image.repo }}/rs-payment:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.payment.gateway }}
          - name: PAYMENT_GATEWAY
            value: {{ .Values.payment.gateway }}
        {{- end }}
        {{- if .Values.payment.failureHour }}
        - name: FAILURE_HOUR
          value: {{ .Values.payment.failureHour | quote }}
        {{- end }}
        {{- if .Values.payment.failureFromMinute }}
        - name: FAILURE_FROM_MINUTE
          value: {{ .Values.payment.failureFromMinute | quote }}
        {{- end }}
        {{- if .Values.payment.failureTillMinute }}
        - name: FAILURE_TILL_MINUTE
          value: {{ .Values.payment.failureTillMinute | quote }}
        {{- end }}
        {{- if .Values.otlp.endpoint }}
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: {{ .Values.otlp.endpoint }}
        {{- end }}
        {{- if .Values.otlp.insecure }}
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: {{ .Values.otlp.insecure | quote }}
        {{- end }}
        {{- if .Values.otlp.headers }}
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: {{ .Values.otlp.headers | quote }}
        {{- end }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=payment,service.namespace=robot-shop"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      {{- with .Values.payment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.payment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.payment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
